{#
    This macro returns the description of the prvdr_state_cd 
#}

{% macro state_description(prvdr_state_cd) -%}

    case {{ dbt.safe_cast(prvdr_state_cd, api.Column.translate_type("text")) }}   
        when '01' then 'Alabama'
        when '02' then 'Alaska'
        when '03' then 'Arizona'
        when '04' then 'Arkansas'
        when '05' then 'California'
        when '06' then 'Colorado'
        when '07' then 'Connecticut'
        when '08' then 'Delaware'
        when '09' then 'District of Columbia'
        when '10' then 'Florida'
        when '11' then 'Georgia'
        when '12' then 'Hawaii'
        when '13' then 'Idaho'
        when '14' then 'Illinois'
        when '15' then 'Indiana'
        when '16' then 'Iowa'
        when '17' then 'Kansas'
        when '18' then 'Kentucky'
        when '19' then 'Louisiana'
        when '20' then 'Maine'
        when '21' then 'Maryland'
        when '22' then 'Massachusetts'
        when '23' then 'Michigan'
        when '24' then 'Minnesota'
        when '25' then 'Mississippi'
        when '26' then 'Missouri'
        when '27' then 'Montana'
        when '28' then 'Nebraska'
        when '29' then 'Nevada'
        when '30' then 'New Hampshire'
        when '31' then 'New Jersey'
        when '32' then 'New Mexico'
        when '33' then 'New York'
        when '34' then 'North Carolina'
        when '35' then 'North Dakota'
        when '36' then 'Ohio'
        when '37' then 'Oklahoma'
        when '38' then 'Oregon'
        when '39' then 'Pennsylvania'
        when '40' then 'Puerto Rico'
        when '41' then 'Rhode Island'
        when '42' then 'South Carolina'
        when '43' then 'South Dakota'
        when '44' then 'Tennessee'
        when '45' then 'Texas'
        when '46' then 'Utah'
        when '47' then 'Vermont'
        when '48' then 'Virgin Islands'
        when '49' then 'Virginia'
        when '50' then 'Washington'
        when '51' then 'West Virginia'
        when '52' then 'Wisconsin'
        when '53' then 'Wyoming'
        when '54' then 'Africa'
        when '55' then 'Asia'
        when '56' then 'Canada'
        when '57' then 'Central America and West Indies'
        when '58' then 'Europe'
        when '59' then 'Mexico'
        when '60' then 'Oceania'
        when '61' then 'Philippines'
        when '62' then 'South America'
        when '63' then 'U.S. Possessions'
        when '64' then 'American Samoa'
        when '65' then 'Guam'
        when '66' then 'Commonwealth of the Northern Marianas Islands'
        when '97' then 'Northern Marianas'
        when '98' then 'Guam'
        when '99' then 'Unknown or if county code = 000, then this is American Samoa'
        else 'UNKNOWN'
    end

{%- endmacro %}