{{
    config(
        materialized='table'
    )
}}

with hospice_data as (
    select *
    from {{ ref('int_hospice') }}
)
select 
    bene_id,
    clm_id,
    nch_near_line_rec_ident_cd,
    nch_clm_type_cd,
    claim_type_desc,
    clm_from_dt,
    clm_thru_dt,
    nch_wkly_proc_dt,
    fi_clm_proc_dt,
    prvdr_num,
    clm_fac_type_cd,
    facility_type,
    clm_srvc_clsfctn_type_cd,
    claim_service_type,
    clm_freq_cd,
    fi_num,
    clm_mdcr_non_pmt_rsn_cd,
    clm_pmt_amt,
    nch_prmry_pyr_clm_pd_amt,
    nch_prmry_pyr_cd,
    prvdr_state_cd,
    prvdr_state,
    org_npi_num,
    at_physn_upin,
    at_physn_npi,
    ptnt_dschrg_stus_cd,  
    patient_discharge_status,
    clm_tot_chrg_amt,
    nch_ptnt_status_ind_cd,
     patient_discharge_ind,
    clm_utlztn_day_cnt,
    nch_bene_dschrg_dt,
    prncpal_dgns_cd,  
    prncpal_dgns_code_desc,
    fst_dgns_e_cd,
    fst_dgns_e_code_desc,
    clm_hospc_start_dt_id,
    bene_hospc_prd_cnt,
    claim_query_code,
    clm_line_num,
    rev_cntr,
    rev_cntr_dt,
    hcpcs_cd,
    hcpcs_cd_desc,
    rev_cntr_unit_cnt,
    rev_cntr_rate_amt,
    rev_cntr_prvdr_pmt_amt,
    rev_cntr_bene_pmt_amt,
    rev_cntr_pmt_amt_amt,
    rev_cntr_tot_chrg_amt,
    rev_cntr_ncvrd_chrg_amt,
    rev_cntr_ddctbl_coinsrnc_cd,
    rev_cntr_ndc_qty,
    rev_cntr_ndc_qty_qlfr_cd,
    rndrng_physn_upin,
    rndrng_physn_npi

from hospice_data